### PR TITLE
add experimental functional syntax

### PR DESCRIPTION
**Pull request by astampoulis**
This adds support for functional syntax, inspired by the [Idris !-notation](http://docs.idris-lang.org/en/latest/tutorial/interfaces.html#notation) and also the [Ciao functional syntax](http://ciao-lang.org/ciao/build/doc/ciao.html/fsyntax_doc.html) as pointed out by @suhr. Prompted by a discussion in #83.

It is quite bare-bones for now, allowing us to do things like `functional.do !(plus 5 !(plus 5 10)) X` instead of the more cumbersome `plus 5 10 A, plus 5 A X`. Could be generalized to also include `let!`-notation; to handle some form of monadic code; and to provide some syntax for functional clauses where the lift hoisting happens statically rather than dynamically.

Note that this is experimental so it might change. I have made the module opt-in for now, so you'll have to do `%use functional.` in your files if you want to use this!

Also adds `minus` for ints and some tests for the builtins.

### CODE REVIEW

**Comment by brendanzab** [comment]
Is it possible to mix logical code anf functional code with this? Eg.

```
readback !(plus Length 1) OutputType OutputType'
```

I'm unsure where to put the `functional.do`.

**Comment by astampoulis** [comment]
@brendanzab For this example I would probably do `functional.do !(readback !(plus Length 1) OutputType) OutputType'`. More general mixing should be possible too (e.g. where the delineation happens at the rule level), but starts running into issues with builtins that introduce variables, that's why this is more limited for now.

**Comment by brendanzab** [comment]
Ahh right! Yeah I think for `readback` that might be ok. For `is_equal` it's a bit more annoying:
```
functional.do !(is_equal !(plus Length 1)  SecondType1) SecondType2
```
Here `SecondType2` is a bit more like an input, but I have to put it as result, which reads a bit weird. I might just stick to predicates in this case…

**Comment by brendanzab** [comment]
Ohhh, I just realised I can do:

```
set.map (fun Label => functional.do (
    is_equal Length !(eval Values1 !(map.find Clauses1 Label))
                    !(eval Values2 !(map.find Clauses2 Label))
) _) Labels1,
```
ie. I don't need everything to use `!`. Would be cool if there was an unary overload for `functional.do`, so I could write this instead:

```
set.map (fun Label => functional.do (
    is_equal Length !(eval Values1 !(map.find Clauses1 Label))
                    !(eval Values2 !(map.find Clauses2 Label))
)) Labels1,
```

**Comment by brendanzab** [comment]
Hum, although this actually gives me an internal assertion failure in my tests, so now I'm kind of terrified that it _doesn't_ actually do what I expect:

```
    readback Length (enum_elim (choice_closure Values Clauses)) (enum_elim Clauses') :-
        map.mapvalues (fun Elem Elem' =>
            functional.do (readback !(length Values) !(eval Values Elem) Elem') _
        ) Clauses Clauses'.
```
```
$ makam test/init --run-tests

	Makam, version 0.7.35


-- Query result in <command-line>:1:1-12:


=== RUNNING TESTS (test suites: all)
Fatal error: exception File "termlang/termlangprolog.ml", line 1261, characters 6-12: Assertion failed
```
Note that I'm doing `functional.do (readback !(length Values) !(eval Values Elem) Elem') _` because I want to be consistent in how I call `readback` (ie. when I invoke  it in other places I use it as a predicate, and I'd rather be consistent).

**Comment by astampoulis** [comment]
Hm, that's a scary error message, sorry about that.

I don't think that works as you would expect for this -- the first argument of `functional.do` should always be a `lift` (a `!`), otherwise things don't work as expected. The "functional code" is supposed to return a result -- it should roughly be equivalent to an `A -> prop` predicate, but in your case, it's really just a prop.

The fix would indeed be to have a "nonary" `functional.do` for this kind of code where no result is to be returned; and also to make `functional.do` fail if its argument is not a `lift`.

I've been having issues with ssh access to Github today, so can't fix that right now unfortunately, but this should be a quick fix.

**Pull request merged**
