### PR TITLE
The `mult` primitive was wrong in some cases.

### PR DESCRIPTION
**Pull request by teofr**
The `mult` primitive was doing integer division when either the first or second argument was uninstantiated.

This gave the following funky results:

```
# mult 3 R 1 ?
Yes:
R := 0.

# mult 3 0 1 ?
Impossible.

# (mult 3 R 1, mult 3 R 1) ?
Impossible.
```
> The last one by @curiousleo

This solution calculates the quotient and the remainder, and it fails if the remainder is not zero.

_**Disclaimer:** This is the first time I write ocaml, there may be a better/more idiomatic way to do it_

### CODE REVIEW

**Comment by curiousleo** [comment]
Cool. I'm not sure how Makam source code is tested, but this seems like the kind of thing that lends itself to a nice little unit test.

**Comment by astampoulis** [comment]
Thank you @teofr! The OCaml code looks good!

I agree with @curiousleo's suggestion; a good place for a test would be the `stdlib/tests.makam` file where the `string` tests are.

Also since this is changing the Makam core, we'll need to do a version update: `./scripts/makam-version.sh update 0.7.21`

**Comment by teofr** [comment]
Will do the tests and the version update later today.

I was also thinking about adding a more powerful primitive
```
div : int -> int -> int -> int -> prop.
div X Y Q R :-
  "X = Y*Q + R"
```

And then implementing `mult` as
```
mult X Y Z :-
  div Z X Y 0.
```
Do you think this would make sense?

**Comment by astampoulis** [comment]
Yes, I think that would be great! A couple suggestions that might help:

- in the OCaml implementation of the `div` primitive, you'll have to change the `convertfunc` to take a function of three arguments rather than two
- also, there will be four cases to cover corresponding to where the unification variable might show up (`div X N1 N2 N3`, `div N1 X N2 N3`, etc.)
- you can completely remove the `mult` primitive implemented in OCaml, and add a `stdlib/int.makam` library for additional predicates on `int`s, such as `mult`, which you'll have to include in `stdlib/init.makam`.

**Comment by teofr** [comment]
Awesome, will do the changes later then.

I think there are only three cases though, (`div X N1 N2 N3`, `div N1 X N2 N3`, `div N1 N2 X Y`). This would mean I can't use `new_builtin_predicate_from_functions`.
A more natural approach (but less natural for the end user) is to have `div : int -> int -> (int, int) -> prop.`

I'll try to not use `new_builtin_predicate_from_functions`, but if it turns out to be harder than I think, I could add `div : int -> int -> int -> int -> prop.` on `int.makam`.

**Comment by astampoulis** [comment]
You're right, did not think of that!

The core code is quite messy unfortunately, so if not using `new_builtin_predicate_from_functions` ends up being tricky, a builtin `div` with a tuple as the last argument and a wrapper for that in `int.makam` is a good approach.

**Comment by teofr** [comment]
This `mult` thing keeps on giving, I also realized is not that trivial to write `mult` from `div`, since you have to check not to divide by 0.

Also, on the current implementation this happens:
```
# mult 0 R 0 ?
Impossible.
```

I'd like to have the following:
```
# mult 0 R 0 ?
Yes:
R := R.
```
I'll try to do the simplest fix that works and ask for review then.

**Comment by teofr** [comment]
Also: on `div`, if someone asks for `div 3 R 0 3 ?` we need first to check that 3 = 3, and then R can be anything > 3 or < -3. Which is a pain in the ass.

Looking at how Prolog solves it, they add modes to it ([`divmod(+Dividend, +Divisor, -Quotient, -Remainder)`](https://github.com/SWI-Prolog/swipl-devel/blob/c2b0232935f995aadff87e2cab76265dd1203818/src/pl-arith.c#L365)), which is not ideal, but it's also not ideal to have a super complex operation just for the sake of being flexible with regards of what argument you can leave uninstantiated.

@astampoulis let me know what you think of this.

**Comment by astampoulis** [comment]
So I think we should go with something like the Prolog approach, namely that `mult X Y R` and `div X Y Q R` only work when both `X` and `Y` are concrete, and fail otherwise. I do not think we are getting a significant benefit from supporting more modes for these operations, and things do get confusing.

(I have thought before of doing the same for `plus` and adding a corresponding `minus` predicate, but I would rather we not do that right in this PR: the extra modes are used in a few examples outside this repository. I'll keep a note though that that should change.)

**Comment by teofr** [comment]
Implemented the new ideas and updated to `0.7.21`.

**Comment by astampoulis** [comment]
@teofr Thank you very much, this looks great!

(Seems like CircleCI worked ok for the forked build, I'll open a PR just so that Travis CI runs and builds the MacOS binary. But will merge soon!)

**Comment by astampoulis** [comment]
Merged in #62

**Pull request closed without merging**
