### PR TITLE
starting out with stlc

### PR DESCRIPTION
**Pull request by astampoulis**
A small PR starting out with the simply-typed lambda calculus. Next steps -- fleshing out more of System F, and I'll see if I can reuse the code on my blog to get nice HTML for this. 

(BTW, added the `:-` notation in addition to `<-` for premises in Makam which is what most λProlog/Prolog implementations use.)

Feel free to comment in-line! 

@achlipala

### CODE REVIEW

**Comment by astampoulis** [comment]
Oh, in order to run this -- after installing/upgrading Makam, just clone this repository and do
`makam examples/paper/01-base-language.makam -`. The `-` part is to give you the repl after loading the file.

**Comment by achlipala** [comment]
Looking at it now!

BTW, a funny corner case to report: for Makam 'make clean' doesn't work, after upgrading to a new OCaml version, because it calls OCaml, which complains about an incompatibility between two compiled object files!

**Comment by achlipala** [comment]
Looks good to me, after a few typo fixes, etc.!

One surprising issue: this query doesn't terminate.  Do you know why?
`typeof E (arrow T T') ?`

**Comment by astampoulis** [comment]
Great, thanks Adam! I guess the `make clean` issue is because of the `ocamlbuild` plugin coming from a different version, not sure if there's a fix.
As for the non-termination issue: Makam tries rules in sequence, so since the typing rule for `app E E'` is first, it keeps firing. I had at some point looked into having breadth-first search, but it would need quite a bit of refactoring of how the logic programming engine works.

**Comment by achlipala** [comment]
Oh, OK.  Then we can just steer clear of such examples for now.

**Pull request merged**
